### ISSUE TITLE
Lag when typing on iPad iOS 9

### ISSUE THREAD

**Issue by amccullough19** [filamentgroup/auto-complete#10]
When typing to search for an option on an iPad (versions tested were iOS 9.1 and 9.2) there is a noticable lag in the characters appearing on the screen.  The same is true for when removing characters by using the Backspace key.

**Comment by johnbender** [comment]
@amccullough19 

I made some changes to the way we process keypresses that will hopefully speed things up a bit, though I have to confess I had a hard time reproducing any lag time using the keys on an iPad in our demo. 

Can you clone the repo and open `index.html` at the root of the project and give it a whirl? If you need some help getting it set up I can do that too. I'm working on getting the demo hosted on github pages updated in the meantime.

**Comment by johnbender** [comment]
@amccullough19 

The demo has been updated with the latest:

http://filamentgroup.github.io/auto-complete/

Can you test on your iPad? I've been unable to reproduce the issue in our demo page.
