### ISSUE TITLE
Option to run different filtering algorithm / regex

### ISSUE THREAD

**Issue by amccullough19** [filamentgroup/auto-complete#11]
Having only the one algorithm to filter results limits the functionality available for filtering various results.  For example - having two possible options - "United States of America" and "United Kingdom".  Currently if the user types "United", then both options will appear but if the user enters "America" we would like for the filtering to pick up on "United States of America".

Is there a possibility of having the ability to change the search / regex used?

**Comment by johnbender** [comment]
As a workaround this can be accomplished by extending `AutoComplete` and overriding the `compareDataItem` method. 

Example:

```
(function( w, $ ){
  "use strict";

  var AutoCompleteNewDataComparison = function( element, menu ){
    w.componentNamespace.AutoComplete.call( this, element, menu );
  }

 AutoCompleteNewDataComparison.prototype.compareDataItem = function(data, val){
    // your code here to compare the data item which is hopefully a string and 
    // the value of the input
  };
})(this, this.jQuery);
```

With that in place you just need to modify the `init.js` to take into account your custom constructor.

https://github.com/filamentgroup/auto-complete/blob/master/src/init.js#L22

```
...
      if( $this.is("[data-autocomplete]") ){
        autocomplete = new w.componentNamespace.AutoComplete( this, menu );
=>    } else if( $this.is("[YOUR NEW DATA ATTRIBUTE]") ){
=>      autocomplete = new w.componentNamespace.AutoCompleteNewDataComparison( this, menu );
      } else if( $this.is("[data-autocomplete-ajax-html]") ){
        autocomplete = new w.componentNamespace.AutoCompleteAjaxHtml( this, menu );
      } else {
        autocomplete = new w.componentNamespace.AutoCompleteDom( this, menu );
        ...
      }
...
```

**Comment by johnbender** [comment]
Alternately you can just override the existing auto complete `compareDataItem` on whichever version you're using:

For example if you wanted to alter the vanilla `AutoComplete` you would do:

```
w.componentNamespace.AutoComplete.prototype.compareDataItem = function(data, val){
   // do some work here and return true or false
}
```

This way you don't have to alter the `init.js` file.

**Comment by johnbender** [comment]
https://github.com/filamentgroup/auto-complete/blob/master/README.md#custom-comparison-logic

Made it official
