### ISSUE TITLE
Regression with arrow keys and menu

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/auto-complete#2]
![](https://dl.dropboxusercontent.com/u/361291/autocomplete-issue.gif)

Hitting the arrow keys calls render again every time, which blows away the selected value.

It looks like gh-pages is still working (and a bit outdated) so this is probably a recent regression.

I have a fix for this working locally and I’ll PR it, you might have a better way to solve this.

**Comment by johnbender** [comment]
@zachleat 

So I'm wondering if the `suggest` method might be getting called and the down arrow key might not be getting ignored. You can see that the [keydown binding](https://github.com/filamentgroup/auto-complete/blob/master/src/init.js#L37) for the `navigate` method is being fired as evidenced by the highlight, but then it looks like `render` is being called but should be rejected in the `suggest` method here:

https://github.com/filamentgroup/auto-complete/blob/master/src/core.js#L85

Another note, if we do change the menu we should change the main repo too.

**Comment by zachleat** [comment]
@johnbender Shoestring doesn’t do {} on $.each (yet?), added a dev error on the shoestring PR above.

**Comment by zachleat** [comment]
Also merged those other changes to Menu.
