### ISSUE TITLE
Option to disallow entries not in the data.

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/auto-complete#5]
If not a valid entry present in the data source:
- Select best match on blur
- If no matches apply, clear any text in the field.

This might be better tied to a validation framework?

**Comment by johnbender** [comment]
Note: "best match" == "first match"

**Comment by johnbender** [comment]
@zachleat 

Is the second property supposed to also be on blur?

**Comment by johnbender** [comment]
@zachleat 

The first of these two is supported, I'll talk with you about the second tomorrow.
