### ISSUE TITLE
Matching second character bugs

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/auto-complete#6]
![](https://dl.dropboxusercontent.com/u/361291/autocomplete-issue-matching.gif)

This started when we fixed the keycode thing. It just isn’t re-rendering now after the first character is entered.

**Comment by johnbender** [comment]
@zachleat 

Mind giving this a test?

**Comment by zachleat** [comment]
LGTM! I assume you didn’t mean “give a test” as in “write a test” since it appears you did that.
